StoreApp/Models/Group.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StoreApp.Models
{
    public class Group
    {
        public long GroupId { get; set; }
        public string GroupName { get; set; }
        public string Description { get; set; }
        public DateTime RecordDateTimeStamp { get; set; }

        public ICollection<User> Users { get; set; }

        
    }
}

StoreApp/Models/Groups.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StoreApp.Models
{
    public class Groups
    {
        public long groupId { get; set; }
        public string groupName { get; set; }

    }
}

StoreApp/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using StoreApp.Data.Models;

namespace StoreApp.Controllers
{
    [Authorize]
    public class GroupController : Controller
    {
        private readonly ILogger _logger;
        private StoreContext db;
        public GroupController(StoreContext context, ILogger<GroupController> logger)
        {
            _logger = logger;
            db = context;
        }

        public IActionResult Index()
        {           
            var category = db.Groups;
            ViewBag.sessionUserName = HttpContext.Session.GetString("username");
            _logger.LogInformation("Просмотрена страница групп пользователем <<{0}>>", HttpContext.Session.GetString("userLogin"));
            return View(category);
        }



        // GET: Products/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Products/Create

        [HttpPost]
        public async Task<IActionResult> Create([Bind("GroupName, Description, RecordDateTimeStamp ")] Group group)
        {
            if (ModelState.IsValid)
            {
                Group usergroup = await db.Groups.FirstOrDefaultAsync(u => u.GroupName.ToLower() == group.GroupName.ToLower());
                if (usergroup == null)
                {
                    group.RecordDateTimeStamp = DateTime.Now;
                    db.Add(group);
                    await db.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("", "Такая группа уже зарегистрирована в базе данных");
                    _logger.LogError("Такая группа {0} уже зарегистрирована в базе данных", group.GroupName);
                }
                    
            }
            return View(group);
        }


       

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
          
            if (id == null)
            {
                return NotFound();
            }

            var product = await db.Groups.FirstOrDefaultAsync(m => m.GroupId == id);
            if (product == null)
            {
                return NotFound();
            }

            return  View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
          
            var product = await db.Groups.FindAsync(id);
            db.Groups.Remove(product);
            await db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            
            if (id == null)
            {
                return NotFound();
            }

            var group = await db.Groups.FindAsync(id);
            if (group == null)
            {
                return NotFound();
            }
            return View(group);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("GroupId,GroupName,Description")] Group group)
        {
           
            group.RecordDateTimeStamp = DateTime.Now;
            if (id != group.GroupId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {

                Group usergroup = await db.Groups.FirstOrDefaultAsync(u => u.GroupName.ToLower() == group.GroupName.ToLower());
                if (usergroup == null)
                {
                    try
                    {
                        db.Update(group);
                        await db.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!ProductExists(group.GroupId))
                            {
                                return NotFound();
                            }
                        else
                            {
                                throw;
                            }
                    }
                    return RedirectToAction(nameof(Index));
                }
                else ModelState.AddModelError("", "Такая группа уже зарегистрирована в базе данных");



                
            }
            return View(group);
        }

        private bool ProductExists(long id)
        {
          
            return db.Groups.Any(e => e.GroupId == id);
        }

    }
}

StoreApp/Views/Group/Create.cshtml
@model Group

<h1 class="m-3">Создание новой группы</h1>

<div class="row">
    <div class="col-md-4 m-2">
        <form asp-controller="Group" asp-action="Create" method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label asp-for="GroupName" class="control-label">Введите наименование группы</label>
                <input asp-for="GroupName" class="form-control" />
                <span asp-validation-for="GroupName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Введите описание группы</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input type="submit" value="Создать группу" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Вернуться назад</a>
</div>

StoreApp/Views/Group/Delete.cshtml
@model Group

@{
    ViewData["Title"] = "Delete";
}

<h3 class="m-4">Удаление</h3>

<h4 class="m-3">Вы действительно хотите удалить этот элемент?</h4>
<div>
    
    <hr />
    <dl class="row m-1">
        <dt class="col-sm-3">
            <label asp-for="GroupName" class="control-label">Наименование группы</label>            
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.GroupName)
        </dd>
        <dt class="col-sm-3">
            <label asp-for="Description" class="control-label">Наименование описания</label>
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-3">
            <label asp-for="RecordDateTimeStamp" class="control-label">Дата создания</label>
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RecordDateTimeStamp)
        </dd>
    </dl>

    <form asp-action="Delete" class="m-3">
        <input type="hidden" asp-for="GroupId" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
        <a asp-action="Index">Вернуться назад</a>
    </form>
</div>

StoreApp/Views/Group/Edit.cshtml
@model Group

@{
    ViewData["Title"] = "Edit";
}

<h1>Редактирование группы</h1>


<hr />
<div class="row m-2">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="GroupId" />
            <div class="form-group">
                <label asp-for="GroupName" class="control-label"></label>
                <input asp-for="GroupName" class="form-control" />
                <span asp-validation-for="GroupName" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

StoreApp/Views/Group/Index.cshtml
@model IEnumerable<Group>
<div>
    <h3 class="m-3">Список групп</h3>
</div>
<p>
    <a class="m-3" asp-action="Create" asp-controller="Group" method="post">Создать новую группу</a>
</p>

<table class="table table-sm table-bordered col-1 m-2">
    <thead class="bg-primary text-white text-center">
        <tr>
            <th>GroupId</th>
            <th>GroupName</th>
            <th>Description</th>
            <th>RecordDateTimeStamp</th>
        </tr>
    </thead>
    <tbody class="col-1">
        @foreach (var p in Model)
        {
            <tr>
                <td width="30"  style="text-align-last:center">
                    @p.GroupId
                </td>
                <td>
                    @p.GroupName
                </td>
                <td>
                    @p.Description
                </td>
                <td width="20">
                    @p.RecordDateTimeStamp
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@p.GroupId">Редактировать</a>                    
                </td>
                <td>
                    <a asp-action="Delete" asp-route-id="@p.GroupId">Удалить</a>
                </td>
            </tr>   
        }
   </tbody>
   
    </table>

StoreApp/Views/Group/List.cshtml
@model IEnumerable<Group>
    <div>
        <h3>Список групп</h3>
    </div>
    @foreach (var p in Model)
    {

        <div>
            GroupId: @p.GroupId   <br />
            GroupName: @p.GroupName  <br />
        </div>
        <div> Дата создания @p.RecordDateTimeStamp</div>
        <br />
    }